ROADMAP = {
"01-core": ("Swift itself", "Learn the language before fighting a UI framework at the same time.", {
 "01-beginner": [
  ("playground-drills",    "optionals, enums, closures, protocols"),
  ("fizzbuzz-warmup",      "control flow, ranges, string interpolation"),
  ("struct-vs-class",      "value vs reference semantics, mutation, copies"),
  ("collections-drills",   "map/filter/reduce, Dictionary, Set, sorting"),
  ("string-toolkit",       "String indices, unicode, formatting"),
  ("number-guessing-game", "loops, random, reading stdin, input validation"),
  ("json-parser",          "Codable, nested types, decoding strategies"),
  ("error-handling",       "throws, Result, optionals vs errors"),
  ("date-calculator",      "Date, Calendar, DateComponents, formatters"),
  ("temperature-cli",      "a first end-to-end CLI with no dependencies"),
 ],
 "02-intermediate": [
  ("wc-clone",             "ArgumentParser, file I/O, SPM executables"),
  ("grep-clone",           "Swift Regex, RegexBuilder, streaming input"),
  ("todo-cli",             "JSON persistence on disk, subcommands"),
  ("http-client-cli",      "URLSession from a CLI, async main, exit codes"),
  ("generics-drills",      "constraints, associated types, opaque returns"),
  ("protocol-drills",      "existentials, protocol witnesses, composition"),
  ("property-wrappers",    "custom wrappers, @dynamicMemberLookup"),
  ("result-builders",      "custom @resultBuilder, how SwiftUI's DSL works"),
 ],
 "03-advanced": [
  ("concurrency-drills",   "async/await, structured concurrency, Sendable"),
  ("actors-playground",    "actor isolation, data races, reentrancy"),
  ("async-sequences",      "AsyncStream, custom AsyncSequence, back-pressure"),
  ("task-groups-scheduler","task groups, cancellation, priority, timeouts"),
  ("memory-and-arc",       "retain cycles, weak/unowned, Instruments leaks"),
  ("swift-macro",          "compile-time metaprogramming, SwiftSyntax"),
  ("mini-interpreter",     "lexer/parser/evaluator, indirect enums, recursion"),
 ]}),

"02-desktop": ("macOS", "Desktop-shaped UI: windows, menus, the file system, AppKit underneath.", {
 "01-beginner": [
  ("unit-converter",       "@State, Form, Picker on macOS"),
  ("calculator",           "Grid layout, keyboard input, focus"),
  ("color-picker",         "ColorPicker, NSPasteboard, AppKit interop"),
  ("sticky-notes",         "WindowGroup, multi-window, @SceneStorage"),
  ("image-viewer",         "drag & drop, NSOpenPanel, file URLs"),
  ("pomodoro-timer",       "Timer, UserNotifications, sound"),
  ("markdown-scratchpad",  "NavigationSplitView, TextEditor, menu commands"),
 ],
 "02-intermediate": [
  ("menubar-utility",      "MenuBarExtra, LSUIElement, SMAppService, AppStorage"),
  ("clipboard-history",    "NSPasteboard polling, persistence, global hotkey"),
  ("api-dashboard",        "async networking, loading/error states, caching"),
  ("rss-reader",           "XML parsing, SwiftData, three-column split view"),
  ("file-organizer",       "FileManager batch ops, progress, undo"),
  ("system-monitor",       "host statistics, Swift Charts, timers"),
  ("markdown-editor",      "live preview, export, find & replace"),
 ],
 "03-advanced": [
  ("document-app",         "DocumentGroup, UTType, sandboxing, bookmarks"),
  ("window-manager",       "Accessibility APIs, AXUIElement, global hotkeys"),
  ("launcher",             "Spotlight-style, fuzzy search, NSEvent monitors"),
  ("screenshot-annotator", "ScreenCaptureKit, Canvas drawing, export"),
  ("metal-image-editor",   "Core Image then custom Metal shaders, GPU profiling"),
  ("terminal-emulator",    "PTY, NSTextView, deep AppKit"),
  ("ship-it",              "signing, notarization, Sparkle updates, a website"),
 ]}),

"03-mobile": ("iOS", "Touch-shaped UI: one window, sensors, the App Store.", {
 "01-beginner": [
  ("tip-calculator",       "@State, Form, Picker"),
  ("dice-roller",          "animations, randomness, view composition"),
  ("bmi-calculator",       "Slider, computed properties, conditional styling"),
  ("rock-paper-scissors",  "enums driving views, game state"),
  ("unit-converter",       "Measurement, formatters, @FocusState"),
  ("stopwatch",            "Timer, TimelineView, app lifecycle"),
  ("flashcards",           "NavigationStack, @Binding, gestures"),
  ("color-palette",        "LazyVGrid, ShareLink, clipboard"),
  ("quote-of-the-day",     "a first network call, .refreshable"),
  ("todo-list",            "List, swipe actions, @AppStorage"),
 ],
 "02-intermediate": [
  ("weather",              "async/await, Codable, CoreLocation, permissions"),
  ("movie-search",         "API pagination, AsyncImage, debounced search"),
  ("habit-tracker",        "SwiftData, @Query, Swift Charts, notifications"),
  ("expense-tracker",      "date grouping, charts, CSV export"),
  ("recipe-book",          "SwiftData relationships, search, filtering"),
  ("photo-journal",        "PhotosPicker, camera, @Observable"),
  ("workout-timer",        "HealthKit basics, background audio, haptics"),
  ("notes-sync",           "iCloud key-value store, first taste of conflicts"),
 ],
 "03-advanced": [
  ("widget-live-activity", "WidgetKit, App Intents, ActivityKit"),
  ("custom-camera",        "AVFoundation capture pipeline, manual controls"),
  ("maps-explorer",        "MapKit, annotations, clustering, region queries"),
  ("audio-recorder",       "AVAudioEngine, waveform rendering, Canvas"),
  ("vision-ml-tool",       "Vision, Core ML, on-device inference"),
  ("offline-sync",         "CloudKit, conflict resolution, background refresh"),
  ("performance-lab",      "Instruments, list performance, memory pressure"),
  ("ship-it",              "provisioning, TestFlight, App Review, privacy manifest"),
 ]})}
